export class Cities {
  public static readonly CITIES: readonly string[] = [
    'Alagoinhas',
    'Barreiras',
    'Bom Jesus da Lapa',
    'Brumado',
    'Cachoeira',
    'Cama\u00e7ari',
    'Candeias',
    'Cruz das Almas',
    'Eunapolis',
    'Feira de Santana',
    'Guanambi',
    'Ilh\u00e9us',
    'Irec\u00ea',
    'Itabuna',
    'Itaberaba',
    'Jacobina',
    'Jequi\u00e9',
    'Juazeiro',
    'Lauro de Freitas',
    'Paulo Afonso',
    'Porto Seguro',
    'Salvador',
    'Santo Ant\u00f4nio de Jesus',
    'Seabra',
    'Senhor do Bonfim',
    'Serrinha',
    'Sim\u00f5es Filho',
    'Teixeira de Freitas',
    'Valen\u00e7a',
    'Vit\u00f3ria da Conquista',
    'Xique-Xique',
  ];
}
